# Generated by Django 5.2.6 on 2025-09-28 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='요금제 이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격')),
                ('billing_cycle', models.CharField(default='monthly', max_length=50, verbose_name='결제 주기')),
                ('included_units', models.IntegerField(blank=True, null=True, verbose_name='포함된 유닛')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='구독 가격')),
                ('status', models.CharField(choices=[('active', '활성'), ('canceled', '취소됨'), ('expired', '만료됨'), ('pending', '대기중')], default='pending', max_length=20, verbose_name='구독 상태')),
                ('remaining_units', models.IntegerField(blank=True, null=True, verbose_name='남은 유닛')),
                ('start_date', models.DateTimeField(verbose_name='시작일')),
                ('end_date', models.DateTimeField(verbose_name='종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, unique=True, verbose_name='주문 ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='결제 금액')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('success', '성공'), ('failed', '실패'), ('refunded', '환불됨')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=100, verbose_name='결제 수단')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='거래 ID')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='결제일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.plan')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_histories', to='payments.subscription')),
            ],
        ),
    ]
