# Generated by Django 5.2.6 on 2025-10-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_locked_until',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_fail_count',
        ),
    ]
