# Generated by Django 5.2.6 on 2025-10-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_uid',
            field=models.UUIDField(blank=True, help_text='Supabase Auth User ID', null=True, unique=True),
        ),
    ]
