# Generated by Django 5.2.6 on 2025-10-08 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_account_locked_until_and_more'),
        ('users', '0002_user_supabase_uid'),
    ]

    operations = [
    ]
