# PR 리뷰어 자동 할당
addReviewers: true
addAssignees: false
numberOfReviewers: 1 # Reduced to 1 for simplicity, adjust as needed

reviewers:
  - team-lead
  - senior-dev
  - backend-team
  - devops-team # Added devops for relevant changes

# 파일 경로별 전문 리뷰어
filePathReviewers:
  'ai/**':
    - backend-team
  'chat/**':
    - backend-team
  'users/**':
    - backend-team
  'config/**':
    - backend-team
  'migrations/**': # Assuming migrations are in app subdirectories
    - database-admin
    - team-lead
  '.github/**':
    - devops-team
    - team-lead
  '*.md': # For documentation changes
    - tech-writer
    - team-lead

# 스킵 조건
skipDraft: true
skipKeywords:
  - '[WIP]'
  - '[Draft]'
  - 'wip'