[project]
name = "be"
version = "0.1.0"
#dependencies = [
#    "django-two-factor-auth>=1.18.0",
#]

[tool.ruff]
line-length = 88
exclude = ["*/migrations/*.py"]

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "I"]
ignore = []

# 파일별 경고 무시
per-file-ignores = { "__init__.py" = ["F401"], "config/settings.py" = ["E501"] }

[tool.ruff.lint.mccabe]
# "C901": 함수가 너무 복잡할 때 경고
max-complexity = 10

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.coverage.run]
source = ["."]
omit = [
    ".*",
    "*/migrations/*",
    "*/tests/*",
    "manage.py",
    "conftest.py",
    "config/asgi.py",
    "config/wsgi.py",
    "config/celery.py",
    "htmlcov/*",
    "frontend/*",
    "*/site-packages/*",
]

[tool.coverage.report]
fail_under = 80
show_missing = true
