# ???? ?? ??
sonar.projectKey=pystagram
sonar.projectName=Pystagram
sonar.sourceEncoding=UTF-8
sonar.language=py

# ??? ??
sonar.sources=.

# ???? ??? ?? (pytest --cov --cov-report=xml ? ?? coverage.xml)
sonar.python.coverage.reportPaths=coverage.xml

# ??? ?? (coverage on new code ??? ???)
sonar.coverage.exclusions=**/migrations/**,**/tests/**,**/__init__.py,manage.py,fix_schedule_notification.py
sonar.exclusions=**/migrations/**,**/tests/**
