# Generated by Django 5.2.6 on 2025-09-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="is_favorited",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
