"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.
For more information: https://docs.djangoproject.com/en/5.2/topics/settings/
Full list of settings: https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# -----------------------------
# 기본 경로 설정
# -----------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# -----------------------------
# 보안 설정
# -----------------------------
JWT_SECRET_KEY = os.getenv(
    "JWT_SECRET_KEY", os.environ.get("SECRET_KEY", "django-insecure-default-key")
)
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-default-key")
DEBUG = os.environ.get("DEBUG", "0") == "1"

if os.environ.get("RUNNING_TESTS"):
    ALLOWED_HOSTS = ["testserver"]
else:
    ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# -----------------------------
# 앱 정의
# -----------------------------
INSTALLED_APPS = [
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 3rd party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    # 2FA 관련 앱 추가
    "django_otp",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_static",
    "two_factor",
    # local apps
    "users",
    "chat",
    "ai",
    "schedule",
    "search",
    "notifications",
    "django_extensions",
]


# -----------------------------
# 미들웨어
# -----------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]


ROOT_URLCONF = "config.urls"


# -----------------------------
# 템플릿 설정
# -----------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# -----------------------------
# 2FA 관련 설정
# -----------------------------
TWO_FACTOR_FORMS = {
    "setup": "two_factor.forms.TOTPDeviceForm",
}
LOGIN_URL = "two_factor:login"
LOGIN_REDIRECT_URL = "/"


# -----------------------------
# WSGI / ASGI
# -----------------------------
WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# -----------------------------
# Channels 설정
# -----------------------------
if os.environ.get("RUNNING_TESTS"):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
        },
    }

# -----------------------------
# 데이터베이스
# -----------------------------
if os.environ.get("RUNNING_TESTS"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": "test_db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "mydatabase"),
            "USER": os.environ.get("DB_USER", "myuser"),
            "PASSWORD": os.environ.get("DB_PASSWORD", "mypassword"),
            "HOST": os.environ.get("DB_HOST", "db"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }

AUTH_USER_MODEL = "users.User"


# -----------------------------
# REST Framework 설정
# -----------------------------
if os.environ.get("RUNNING_TESTS"):
    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": (
            "rest_framework.authentication.SessionAuthentication",
        ),
        "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    }
else:
    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": (
            "rest_framework_simplejwt.authentication.JWTAuthentication",
        ),
        "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    }


# -----------------------------
# JWT 설정
# -----------------------------
SIMPLE_JWT = {
    # 30분으로 단축해 보안성 강화
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    # 7일로 늘려 현실적인 갱신 정책
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    # Refresh 토큰을 재발급하면서 회전
    "ROTATE_REFRESH_TOKENS": True,
    # 갱신 시 이전 토큰 블랙리스트에 추가
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": JWT_SECRET_KEY,
    # Authorization 헤더 타입 지정
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# -----------------------------
# 쿠키 보안
# -----------------------------
SECURE_COOKIE = os.getenv("DEBUG", "0") != "1"
SESSION_COOKIE_SECURE = SECURE_COOKIE
CSRF_COOKIE_SECURE = SECURE_COOKIE


# -----------------------------
# 패스워드 검증
# -----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        )
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -----------------------------
# 국제화
# -----------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# -----------------------------
# 정적 파일
# -----------------------------
STATIC_URL = "static/"

# -----------------------------
# 기본 PK 필드
# -----------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(asctime)s %(name)s %(levelname)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "users": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "chat": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "ai": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# SMTP 서버 설정
EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend"  # 개발 시 이메일 콘솔 출력
)
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend" # 배포 시 사용
EMAIL_HOST = "smtp.gmail.com"  # 구글 SMTP 예시
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get(
    "EMAIL_HOST_USER"
)  # 실제 이메일 아이디 (환경변수로 관리 권장)
EMAIL_HOST_PASSWORD = os.environ.get(
    "EMAIL_HOST_PASSWORD"
)  # 비밀번호(또는 앱 비밀번호)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # 발신 이메일 주소 기본값
