# Generated by Django 5.2.6 on 2025-09-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprocesseddata',
            name='request',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='ModelResult',
        ),
        migrations.DeleteModel(
            name='PreprocessedData',
        ),
        migrations.DeleteModel(
            name='RequestLog',
        ),
    ]
