# Generated by Django 5.2.6 on 2025-09-26 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_link_alter_notification_sender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNotificationPreference',
        ),
    ]
