# Generated by Django 5.2.6 on 2025-10-08 05:57

from django.db import migrations

# 데이터 삽입 함수
def create_initial_notification_types(apps, schema_editor):
    NotificationType = apps.get_model("notifications", "NotificationType")

    initial_types = [
        {"code": "CHAT_MESSAGE", "description": "새로운 채팅 메시지", "default_enabled": True},
        {"code": "SCHEDULE_REMINDER", "description": "일정 알림 (예약)", "default_enabled": True},
        {"code": "PAYMENT_SUCCESS", "description": "결제 완료 알림", "default_enabled": True},
    ]

    for data in initial_types:
        NotificationType.objects.get_or_create(code=data["code"], defaults=data)


# 데이터 롤백 함수
def reverse_initial_notification_types(apps, schema_editor):
    NotificationType = apps.get_model("notifications", "NotificationType")
    NotificationType.objects.filter(
        code__in=["CHAT_MESSAGE", "SCHEDULE_REMINDER", "PAYMENT_SUCCESS"]
    ).delete()


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        # 🚩 종속성: 0003 파일 다음에 실행되도록 설정
        ('notifications', '0003_usernotificationpreference'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_notification_types,
            reverse_code=reverse_initial_notification_types
        ),
    ]