# Generated by Django 5.2.6 on 2025-10-08 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtype'),
        ),
    ]
