# Generated by Django 5.0.7 on 2025-10-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
        ('notifications', '0005_insert_initial_notification_types'),
    ]

    operations = [
    ]
